import { Product, IdHolderTypeConfig, IdHolderColorVariant, StoreSettings } from '@/types';

export const DEFAULT_SETTINGS: StoreSettings = {
  shopName: 'ហាងឯកសណ្ឋានសិស្ស សម្តេចជាស៊ីម',
  location: 'ខាងក្នុងបរិវេណសាលាបឋមសិក្សា សម្តេចជាស៊ីម (មុខអគាររដ្ឋបាល)',
  phone1: '012 345 678',
  phone2: '098 765 432',
  telegram: 'bNha_dev',
  bakongId: 'cheasim_primary@acleda',
  customQrUrl: '',
};

export const ID_HOLDER_TYPES: Record<'set' | 'holder' | 'lanyard', IdHolderTypeConfig> = {
  set: {
    id: 'set',
    labelKh: '១ ឈុត (Set)',
    nameKh: 'ឈុតប្រអប់កាត + ខ្សែពាក់ក (1 Set)',
    nameEn: 'ID Card Set (Holder + Lanyard)',
    priceKhr: 6500,
    priceUsd: 1.59,
    badge: 'ឈុតពេញលេញ',
    hasColor: true,
  },
  holder: {
    id: 'holder',
    labelKh: 'តែប្រអប់កាត',
    nameKh: 'ប្រអប់កាតសិស្ស (Card Holder Only)',
    nameEn: 'School ID Card Holder (Only)',
    priceKhr: 1500,
    priceUsd: 0.37,
    badge: 'តែប្រអប់កាត',
    hasColor: true,
  },
  lanyard: {
    id: 'lanyard',
    labelKh: 'តែខ្សែពាក់ក',
    nameKh: 'ខ្សែពាក់កសិស្ស (Lanyard Only)',
    nameEn: 'School ID Lanyard (Only)',
    priceKhr: 5000,
    priceUsd: 1.22,
    badge: 'តែខ្សែពាក់ក',
    hasColor: true,
  },
};

export const ID_HOLDER_VARIANTS: Record<'blue' | 'orange' | 'green', IdHolderColorVariant> = {
  blue: {
    gradeGroup: 'ថ្នាក់ទី១ - ទី២',
    colorKh: 'ពណ៌ខៀវ',
    badge: 'ថ្នាក់ទី១ - ទី២ (ខៀវ)',
    colorCode: 'blue',
    sizeKey: 'ពណ៌ខៀវ (ថ្នាក់ទី១-២)',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=700&auto=format&fit=crop&q=80',
  },
  orange: {
    gradeGroup: 'ថ្នាក់ទី៣ - ទី៤',
    colorKh: 'ពណ៌ទឹកក្រូច',
    badge: 'ថ្នាក់ទី៣ - ទី៤ (ទឹកក្រូច)',
    colorCode: 'orange',
    sizeKey: 'ពណ៌ទឹកក្រូច (ថ្នាក់ទី៣-៤)',
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=700&auto=format&fit=crop&q=80',
  },
  green: {
    gradeGroup: 'ថ្នាក់ទី៥ - ទី៦',
    colorKh: 'ពណ៌បៃតង',
    badge: 'ថ្នាក់ទី៥ - ទី៦ (បៃតង)',
    colorCode: 'green',
    sizeKey: 'ពណ៌បៃតង (ថ្នាក់ទី៥-៦)',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=700&auto=format&fit=crop&q=80',
  },
};

export interface SizeWeightInfo {
  weight: string;
  height: string;
  gradeHint: string;
}

export const SIZE_WEIGHT_GUIDE: Record<string, SizeWeightInfo> = {
  '20': { weight: '16-19 kg', height: '110-118 cm', gradeHint: 'ថ្នាក់ទី ១' },
  '22': { weight: '19-23 kg', height: '118-125 cm', gradeHint: 'ថ្នាក់ទី ១-២' },
  '24': { weight: '23-27 kg', height: '125-132 cm', gradeHint: 'ថ្នាក់ទី ២-៣' },
  '26': { weight: '27-32 kg', height: '132-138 cm', gradeHint: 'ថ្នាក់ទី ៣-៤' },
  '28': { weight: '32-37 kg', height: '138-145 cm', gradeHint: 'ថ្នាក់ទី ៤-៥' },
  '30': { weight: '37-43 kg', height: '145-152 cm', gradeHint: 'ថ្នាក់ទី ៥-៦' },
  '32': { weight: '43-50 kg', height: '150-158 cm', gradeHint: 'ថ្នាក់ទី ៦ (មាឌធំ)' },
  'M': { weight: '40-47 kg', height: '148-156 cm', gradeHint: 'ថ្នាក់ទី ៥-៦' },
  'L': { weight: '48-55 kg', height: '155-162 cm', gradeHint: 'ថ្នាក់ទី ៦' },
  'XL': { weight: '55+ kg', height: '160+ cm', gradeHint: 'ថ្នាក់ទី ៦ (មាឌធំ)' },
  'ស្តង់ដារ (Free Size)': { weight: 'ទូទៅ', height: 'ទូទៅ', gradeHint: 'គ្រប់កម្រិតថ្នាក់' },
  'ស្តង់ដារ': { weight: 'ទូទៅ', height: 'ទូទៅ', gradeHint: 'គ្រប់កម្រិតថ្នាក់' },
};

export const BASE_PRODUCTS: Product[] = [
  {
    id: 'cs-boy-shirt',
    name: 'Primary Boy Uniform Shirt (White)',
    nameKh: 'អាវសិស្សប្រុសដៃខ្លី ពណ៌ស',
    category: 'boy',
    priceKhr: 18000,
    priceUsd: 4.39,
    badge: 'លក់ដាច់បំផុត',
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=700&auto=format&fit=crop&q=80',
    description: 'អាវសិស្សប្រុសពណ៌សដៃខ្លី កត្រង់ មានប៉ាក់ស្លាកសញ្ញាសាលាបឋមសិក្សាសម្តេចជាស៊ីមនៅលើហោប៉ៅ ក្រណាត់កប្បាសត្រជាក់ស្រួលពាក់។',
    sizes: [
      { size: '20', stock: 25 },
      { size: '22', stock: 35 },
      { size: '24', stock: 40 },
      { size: '26', stock: 30 },
      { size: '28', stock: 18 },
      { size: '30', stock: 12 },
      { size: '32', stock: 5 },
    ],
  },
  {
    id: 'cs-boy-pant',
    name: 'Primary Boy Uniform Short Pants (Navy)',
    nameKh: 'ខោខ្លីសិស្សប្រុស ពណ៌ខៀវចាស់',
    category: 'boy',
    priceKhr: 16000,
    priceUsd: 3.90,
    badge: 'ស្តង់ដាររដ្ឋ',
    image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=700&auto=format&fit=crop&q=80',
    description: 'ខោខ្លីសិស្សប្រុសពណ៌ខៀវចាស់ ចង្កេះកៅស៊ូយឺតចំហៀង ផាសុកភាពខ្ពស់ ធន់នឹងការបោកគក់ ស័ក្តិសមសិស្សបឋមរត់លេង។',
    sizes: [
      { size: '22', stock: 20 },
      { size: '24', stock: 30 },
      { size: '26', stock: 35 },
      { size: '28', stock: 22 },
      { size: '30', stock: 15 },
      { size: '32', stock: 8 },
    ],
  },
  {
    id: 'cs-boy-tie',
    name: 'School Boy Uniform Necktie',
    nameKh: 'ក្រវ៉ាត់កសិស្សប្រុស (Tie)',
    category: 'boy',
    priceKhr: 6000,
    priceUsd: 1.46,
    badge: 'ចាំបាច់',
    image: 'https://images.unsplash.com/photo-1589756823695-278bc923f962?w=700&auto=format&fit=crop&q=80',
    description: 'ក្រវ៉ាត់កពណ៌ខៀវចាស់ផ្លូវការ មានខ្សែយឺតពាក់កស្រួល មិនពិបាកចង សាកសមសម្រាប់សិស្សប្រុសពាក់រាល់ថ្ងៃចន្ទ ឬកម្មវិធីសាលា។',
    sizes: [
      { size: 'ស្តង់ដារ (Free Size)', stock: 85 },
    ],
  },
  {
    id: 'cs-girl-shirt',
    name: 'Primary Girl Uniform Shirt (White/Lotus Collar)',
    nameKh: 'អាវសិស្សស្រីដៃខ្លី កឈូក ពណ៌ស',
    category: 'girl',
    priceKhr: 18000,
    priceUsd: 4.39,
    badge: 'លក់ដាច់បំផុត',
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=700&auto=format&fit=crop&q=80',
    description: 'អាវសិស្សស្រីពណ៌សម៉ូដកឈូកទន់ភ្លន់ ដៃខ្លី មានប៉ាក់ឡូហ្គោសាលា ក្រណាត់ទន់ស្រួល មិនងាយឡើងលឿងពេលបោកគក់។',
    sizes: [
      { size: '20', stock: 20 },
      { size: '22', stock: 30 },
      { size: '24', stock: 45 },
      { size: '26', stock: 28 },
      { size: '28', stock: 15 },
      { size: '30', stock: 10 },
      { size: '32', stock: 6 },
    ],
  },
  {
    id: 'cs-girl-skirt',
    name: 'Primary Girl Uniform Pleated Skirt (Navy)',
    nameKh: 'សំពត់ផ្នត់សិស្សស្រី ពណ៌ខៀវចាស់',
    category: 'girl',
    priceKhr: 16000,
    priceUsd: 3.90,
    badge: 'ស្តង់ដាររដ្ឋ',
    image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=700&auto=format&fit=crop&q=80',
    description: 'សំពត់សិស្សស្រីពណ៌ខៀវចាស់ មានផ្នត់ជុំវិញ ចង្កេះកៅស៊ូយឺត មិនងាយជ្រីវជ្រួញ ងាយស្រួលបោកគក់។',
    sizes: [
      { size: '22', stock: 16 },
      { size: '24', stock: 24 },
      { size: '26', stock: 30 },
      { size: '28', stock: 15 },
      { size: '30', stock: 10 },
      { size: '32', stock: 4 },
    ],
  },
  {
    id: 'cs-sport-uniform',
    name: 'School Sport Uniform Set (Unisex)',
    nameKh: 'ឈុតកីឡាសាលា (អាវយឺត + ខោកីឡា)',
    category: 'sport',
    priceKhr: 26000,
    priceUsd: 6.34,
    badge: 'ពណ៌តាមកម្រិតថ្នាក់',
    image: 'https://images.unsplash.com/photo-1577471488278-16eec37ffcc2?w=700&auto=format&fit=crop&q=80',
    description: 'ឈុតកីឡាផ្លូវការសម្រាប់សិស្សបឋមសិក្សា (អាវយឺត + ខោកីឡា) សាច់ក្រណាត់យឺតទន់ត្រជាក់ ស្រួលរត់លេង។ ជ្រើសរើសពណ៌តាមកម្រិតថ្នាក់៖ ថ្នាក់ ១-២ (ខៀវ), ថ្នាក់ ៣-៤ (ទឹកក្រូច), ថ្នាក់ ៥-៦ (បៃតង)។',
    isVariantGroup: true,
    variants: {
      blue: {
        id: 'cs-sport-blue',
        gradeGroup: 'ថ្នាក់ទី១ - ទី២',
        colorKh: 'ពណ៌ខៀវ',
        badge: 'ថ្នាក់ទី១ - ទី២ (ខៀវ)',
        colorCode: 'blue',
        image: 'https://images.unsplash.com/photo-1577471488278-16eec37ffcc2?w=700&auto=format&fit=crop&q=80',
        sizes: [
          { size: '20', stock: 15 },
          { size: '22', stock: 22 },
          { size: '24', stock: 25 },
          { size: '26', stock: 18 },
          { size: '28', stock: 12 },
          { size: '30', stock: 8 },
          { size: 'M', stock: 6 },
          { size: 'L', stock: 4 },
          { size: 'XL', stock: 3 },
        ],
      },
      orange: {
        id: 'cs-sport-orange',
        gradeGroup: 'ថ្នាក់ទី៣ - ទី៤',
        colorKh: 'ពណ៌ទឹកក្រូច',
        badge: 'ថ្នាក់ទី៣ - ទី៤ (ទឹកក្រូច)',
        colorCode: 'orange',
        image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=700&auto=format&fit=crop&q=80',
        sizes: [
          { size: '20', stock: 8 },
          { size: '22', stock: 12 },
          { size: '24', stock: 20 },
          { size: '26', stock: 28 },
          { size: '28', stock: 24 },
          { size: '30', stock: 16 },
          { size: 'M', stock: 10 },
          { size: 'L', stock: 6 },
          { size: 'XL', stock: 4 },
        ],
      },
      green: {
        id: 'cs-sport-green',
        gradeGroup: 'ថ្នាក់ទី៥ - ទី៦',
        colorKh: 'ពណ៌បៃតង',
        badge: 'ថ្នាក់ទី៥ - ទី៦ (បៃតង)',
        colorCode: 'green',
        image: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=700&auto=format&fit=crop&q=80',
        sizes: [
          { size: '20', stock: 4 },
          { size: '22', stock: 6 },
          { size: '24', stock: 10 },
          { size: '26', stock: 18 },
          { size: '28', stock: 26 },
          { size: '30', stock: 30 },
          { size: 'M', stock: 22 },
          { size: 'L', stock: 15 },
          { size: 'XL', stock: 8 },
        ],
      },
    },
  },
  {
    id: 'cs-id-holder',
    name: 'School ID Card Holder & Lanyard (1 Set)',
    nameKh: 'ប្រអប់កាតសិស្ស និងខ្សែពាក់ក',
    category: 'supplies',
    priceKhr: 6500,
    priceUsd: 1.59,
    badge: 'ឡូហ្គោសាលា',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=700&auto=format&fit=crop&q=80',
    description: 'ប្រអប់ជ័រការពារកាតសិស្ស និងខ្សែពាក់កមានព្រីនឈ្មោះ បឋមសិក្សា សម្តេចជាស៊ីម បែងចែកពណ៌តាមកម្រិតថ្នាក់ (១ ឈុត ៦,៥០០៛ / តែប្រអប់ ១,៥០០៛ / តែខ្សែ ៥,០០០៛)។',
    sizes: [
      { size: 'ពណ៌ខៀវ (ថ្នាក់ទី១-២)', stock: 120 },
      { size: 'ពណ៌ទឹកក្រូច (ថ្នាក់ទី៣-៤)', stock: 95 },
      { size: 'ពណ៌បៃតង (ថ្នាក់ទី៥-៦)', stock: 80 },
    ],
  },
];

// Fallback items for individual stock tracking
export const ACCESSORY_STOCK_ITEMS = [
  {
    id: 'cs-id-holder-only',
    name: 'School ID Card Holder (Only)',
    nameKh: 'ប្រអប់កាតសិស្ស (Card Holder Only)',
    category: 'supplies',
    priceKhr: 1500,
    priceUsd: 0.37,
    sizes: [
      { size: 'ពណ៌ខៀវ (ថ្នាក់ទី១-២)', stock: 150 },
      { size: 'ពណ៌ទឹកក្រូច (ថ្នាក់ទី៣-៤)', stock: 120 },
      { size: 'ពណ៌បៃតង (ថ្នាក់ទី៥-៦)', stock: 100 },
    ],
  },
  {
    id: 'cs-id-lanyard-only',
    name: 'School ID Lanyard (Only)',
    nameKh: 'ខ្សែពាក់កសិស្ស (Lanyard Only)',
    category: 'supplies',
    priceKhr: 5000,
    priceUsd: 1.22,
    sizes: [
      { size: 'ពណ៌ខៀវ (ថ្នាក់ទី១-២)', stock: 100 },
      { size: 'ពណ៌ទឹកក្រូច (ថ្នាក់ទី៣-៤)', stock: 85 },
      { size: 'ពណ៌បៃតង (ថ្នាក់ទី៥-៦)', stock: 70 },
    ],
  },
];
